apiVersion: v1
kind: Service
metadata:
  name: sentinel-demo-com-svc

  labels:
    app: sentinel.demo.com
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: sentinel.demo.com
