apiVersion: v1
kind: Service
metadata:
  name: zipkin-demo-com-svc
 
  labels:
    app: zipkin.demo.com
spec:
  type: ClusterIP
  ports:
  - port: 9411
    targetPort: 9411
  selector:
    app: zipkin.demo.com
